version: '3.4'
services:
  pict_api:
    build:
      context: .
      target: target_for_development
    environment:
      NODE_ENV: development
    container_name: pict_api
    volumes:
      - ./:/root/api/
      - /root/api/front # to ignore front/node_modules
    working_dir: /root/api/
    command: fresh # run `main.go` with auto reload
    ports:
      - '8080:8080'
  pict_react:
    image: node:12.12.0-alpine
    container_name: pict_react
    volumes:
      - ./front:/root/front
      - /root/front/node_modules/
    working_dir: /root/front
    ports:
      - '3000:3000'
    command: sh -c 'yarn && yarn dev'
