# This file is only used in the development enviroment

version: '3.3'
services:
  pict_api:
    build: .
    environment:
      NODE_ENV: development
    container_name: pict_api
    volumes:
      - .:/go/src/github.com/junkboy0315/pairwise-pict-online
    working_dir: /go/src/github.com/junkboy0315/pairwise-pict-online
    command: fresh # run `main.go` with auto reload
    ports:
      - '8080:8080'
  pict_react:
    image: node:12.12.0-alpine
    container_name: pict_react
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    volumes:
      - ./front:/root/front
      - /root/front/node_modules/
    working_dir: /root/front
    ports:
      - '3000:3000'
    command: sh -c 'yarn && yarn start'
