name: my_github_actions

on: [push]

jobs:
  api_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: test server
        run: docker-compose -f docker-compose.test.yml up --exit-code-from pict_api_test
#
